version: "3.5"
services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong_db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - 5432:5432
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "kong"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.3.0
    command: "kong migrations bootstrap"
    networks:
      - kong
      - kong_db
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:1.3.0
    restart: always
    networks:
      - kong
      - kong_db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
#      KONG_PROXY_LISTEN: 0.0.0.0:8000
#      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    depends_on:
      - kong-migration
      - kong-database
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://kong:8001"]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 15
    ports:
      - 8001:8001
      - 8444:8444
      - 8000:8000
      - 8443:8443

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/kong_db"
    networks:
      - kong_db
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong
        - kong_db
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      TOKEN_SECRET: km1GUr4R91839213819283Mpq312
      DB_DATABASE: kong_db
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - 1337:1337


networks:
  kong_db:
    name: kong_db
    driver: bridge
  kong:
    name: kong
    driver: bridge
